import { Release } from "./types";

export const releases: Release[] = [
  {
    id: "dirty-laundry",
    title: "Dirty Laundry",
    subtitle: "Thirteen exes. Every secret I swore I'd never tell.",
    type: "album",
    releaseDate: "2026-02-13",
    artworkPath: "/artwork/dirty-laundry.jpg",
    palette: {
      vibrant: "#06ffa5",
      darkVibrant: "#048a81",
      lightVibrant: "#54fff7",
      muted: "#06bcc1",
      darkMuted: "#054a91",
      lightMuted: "#a8dadc",
      dominant: "#06ffa5",
    },
    streamingLinks: {
      spotify: "https://open.spotify.com/album/2CVgqb9KBzOmjiZbsjpP33",
      appleMusic: "https://music.apple.com/album/dirty-laundry/1870573660",
    },
    featured: true,
  },
  {
    id: "deleted-scenes",
    title: "Deleted Scenes",
    subtitle: "The breakdowns. The imagined romances. Everything I cut from the final take.",
    type: "album",
    releaseDate: "2025-11-01",
    artworkPath: "/artwork/deleted-scenes.jpg",
    palette: {
      vibrant: "#ff6b9d",
      darkVibrant: "#c9184a",
      lightVibrant: "#ffb3c6",
      muted: "#9d4edd",
      darkMuted: "#5a189a",
      lightMuted: "#c8b6ff",
      dominant: "#ff6b9d",
    },
    streamingLinks: {
      spotify: "https://open.spotify.com/album/1OPcQAWFSN4fwS21YP4xoS",
      appleMusic: "https://music.apple.com/us/album/deleted-scenes/1835595581",
    },
  },
  {
    id: "home-in-you",
    title: "A Home In You",
    subtitle: "Morning light. A dog under the duvet. The moment I realised home was a person.",
    type: "ep",
    releaseDate: "2025-10-15",
    artworkPath: "/artwork/home-in-you.jpg",
    palette: {
      vibrant: "#06ffa5",
      darkVibrant: "#048a81",
      lightVibrant: "#54fff7",
      muted: "#06bcc1",
      darkMuted: "#054a91",
      lightMuted: "#a8dadc",
      dominant: "#06ffa5",
    },
    streamingLinks: {
      spotify: "https://open.spotify.com/album/3aUBIOxt5YX5EbNOaoO59v",
      appleMusic: "https://music.apple.com/us/album/a-home-in-you-ep/1838158390",
    },
  },
  {
    id: "sun-drunk-jet-lagged-and-in-love",
    title: "Sun-Drunk, Jet-Lagged & In Love",
    subtitle: "From the airport to the island. And back to myself.",
    type: "album",
    releaseDate: "2025-09-01",
    artworkPath: "/artwork/sun-drunk.jpg",
    palette: {
      vibrant: "#ffd60a",
      darkVibrant: "#fb8500",
      lightVibrant: "#ffea00",
      muted: "#f77f00",
      darkMuted: "#bc6c25",
      lightMuted: "#ffc971",
      dominant: "#ffd60a",
    },
    streamingLinks: {
      spotify: "https://open.spotify.com/album/3hCykL82LlEuRd4vywC7Qe",
      appleMusic: "https://music.apple.com/us/album/sun-drunk-jet-lagged-in-love/1848713050",
    },
  },
  {
    id: "summer-sleigh-ride",
    title: "Summer Sleigh Ride",
    subtitle: "Christmas with no snow. Just sun, irony, and someone worth kissing.",
    type: "ep",
    releaseDate: "2025-08-20",
    artworkPath: "/artwork/summer-sleigh-ride.jpg",
    palette: {
      vibrant: "#ff6b9d",
      darkVibrant: "#c9184a",
      lightVibrant: "#ffb3c6",
      muted: "#9d4edd",
      darkMuted: "#5a189a",
      lightMuted: "#c8b6ff",
      dominant: "#ff6b9d",
    },
    streamingLinks: {
      spotify: "https://open.spotify.com/album/6bFZ7nbEhsh1ThsWiROH4F",
      appleMusic: "https://music.apple.com/us/album/summer-sleigh-ride-single/1860267298",
    },
  },
];
