import Vibrant from "node-vibrant";
import { releases } from "../lib/releases";
import fs from "fs";
import path from "path";

async function extractPalettes() {
  console.log("🎨 Extracting color palettes from artwork...\n");

  const updatedReleases = await Promise.all(
    releases.map(async (release) => {
      const imagePath = path.join(process.cwd(), "public", release.artworkPath);

      // Check if artwork exists
      if (!fs.existsSync(imagePath)) {
        console.log(`⚠️  Artwork not found: ${release.artworkPath}`);
        console.log(`   Using default palette for "${release.title}"`);
        return release;
      }

      try {
        const palette = await Vibrant.from(imagePath).getPalette();

        const extractedPalette = {
          vibrant: palette.Vibrant?.hex || "#ffffff",
          darkVibrant: palette.DarkVibrant?.hex || "#000000",
          lightVibrant: palette.LightVibrant?.hex || "#ffffff",
          muted: palette.Muted?.hex || "#888888",
          darkMuted: palette.DarkMuted?.hex || "#333333",
          lightMuted: palette.LightMuted?.hex || "#cccccc",
          dominant:
            palette.Vibrant?.hex || palette.Muted?.hex || "#ffffff",
        };

        console.log(`✓ Extracted palette for "${release.title}"`);

        return {
          ...release,
          palette: extractedPalette,
        };
      } catch (error) {
        console.log(`⚠️  Error extracting palette for "${release.title}"`);
        console.log(`   Using default palette`);
        return release;
      }
    })
  );

  // Write to a generated file
  const output = `// AUTO-GENERATED — Do not edit manually
// This file is generated by scripts/generate-palettes.ts

import { Release } from "./types";

export const releases: Release[] = ${JSON.stringify(
    updatedReleases,
    null,
    2
  )};
`;

  const outputPath = path.join(process.cwd(), "lib", "releases.generated.ts");
  fs.writeFileSync(outputPath, output);

  console.log("\n✓ Palettes extracted and written to lib/releases.generated.ts");
}

extractPalettes().catch((error) => {
  console.error("Error extracting palettes:", error);
  process.exit(1);
});
